src/AppBundle/Entity/OrderItem.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Sylius\Component\Core\Model\OrderItemInterface;
use Sylius\Component\Core\Model\ProductInterface;
use Sylius\Component\Core\Model\ProductVariantInterface;
use Sylius\Component\Order\Model\AdjustmentInterface;
use Sylius\Component\Order\Model\OrderInterface;
use Sylius\Component\Order\Model\OrderItemInterface as BaseOrderItemInterface;
use Sylius\Component\Order\Model\OrderItemUnitInterface;

class OrderItem implements OrderItemInterface
{
    // BEGIN CUSTOM

    /**
     * @var ShoppingCartItem|null
     */
    protected $shoppingCartItem;

    /**
     * @return ShoppingCartItem|null
     */
    public function getShoppingCartItem(): ?ShoppingCartItem
    {
        return $this->shoppingCartItem;
    }

    /**
     * @param ShoppingCartItem|null $shoppingCartItem
     */
    public function setShoppingCartItem(?ShoppingCartItem $shoppingCartItem): void
    {
        $this->shoppingCartItem = $shoppingCartItem;
    }

    /**
     * @return float
     */
    public function getQuantityFloat(): float
    {
        return $this->quantity;
    }

    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        $this->recalculateUnitsTotal();

        return $this;
    }

    // END CUSTOM

    /**
     * {@inheritdoc}
     */
    public function recalculateUnitsTotal(): void
    {
        $this->unitsTotal = (int)($this->getQuantityFloat() * $this->unitPrice);

        $this->recalculateTotal();
    }

    /** @var mixed */
    protected $id;

    /** @var OrderInterface|null */
    protected $order;

    /** @var float */
    protected $quantity = 0;

    /** @var int */
    protected $unitPrice = 0;

    /** @var int */
    protected $total = 0;

    /** @var bool */
    protected $immutable = false;

    /** @var Collection|OrderItemUnitInterface[] */
    protected $units;

    /** @var int */
    protected $unitsTotal = 0;

    /** @var Collection|AdjustmentInterface[] */
    protected $adjustments;

    /** @var int */
    protected $adjustmentsTotal = 0;

    public function __construct()
    {
        $this->adjustments = new ArrayCollection();
        $this->units = new ArrayCollection();
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    /**
     * {@inheritdoc}
     */
    public function getOrder(): ?OrderInterface
    {
        return $this->order;
    }

    /**
     * {@inheritdoc}
     */
    public function setOrder(?OrderInterface $order): void
    {
        $currentOrder = $this->getOrder();
        if ($currentOrder === $order) {
            return;
        }

        $this->order = null;

        if (null !== $currentOrder) {
            $currentOrder->removeItem($this);
        }

        if (null === $order) {
            return;
        }

        $this->order = $order;

        if (!$order->hasItem($this)) {
            $order->addItem($this);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function getUnitPrice(): int
    {
        return $this->unitPrice;
    }

    /**
     * {@inheritdoc}
     */
    public function setUnitPrice(int $unitPrice): void
    {
        $this->unitPrice = $unitPrice;
        $this->recalculateUnitsTotal();
    }

    /**
     * {@inheritdoc}
     */
    public function getTotal(): int
    {
        return $this->total;
    }

    /**
     * {@inheritdoc}
     */
    public function recalculateAdjustmentsTotal(): void
    {
        $this->adjustmentsTotal = 0;

        foreach ($this->adjustments as $adjustment) {
            if (!$adjustment->isNeutral()) {
                $this->adjustmentsTotal += $adjustment->getAmount();
            }
        }

        $this->recalculateTotal();
    }

    /**
     * {@inheritdoc}
     */
    public function isImmutable(): bool
    {
        return $this->immutable;
    }

    /**
     * {@inheritdoc}
     */
    public function setImmutable(bool $immutable): void
    {
        $this->immutable = $immutable;
    }

    /**
     * {@inheritdoc}
     */
    public function getUnits(): Collection
    {
        return $this->units;
    }

    /**
     * {@inheritdoc}
     */
    public function addUnit(OrderItemUnitInterface $unit): void
    {
        if ($this !== $unit->getOrderItem()) {
            throw new \LogicException('This order item unit is assigned to a different order item.');
        }

        if (!$this->hasUnit($unit)) {
            $this->units->add($unit);

            ++$this->quantity;
            $this->unitsTotal += $unit->getTotal();
            $this->recalculateTotal();
        }
    }

    /**
     * {@inheritdoc}
     */
    public function removeUnit(OrderItemUnitInterface $unit): void
    {
        if ($this->hasUnit($unit)) {
            $this->units->removeElement($unit);

            --$this->quantity;
            $this->unitsTotal -= $unit->getTotal();
            $this->recalculateTotal();
        }
    }

    /**
     * {@inheritdoc}
     */
    public function hasUnit(OrderItemUnitInterface $unit): bool
    {
        return $this->units->contains($unit);
    }

    /**
     * {@inheritdoc}
     */
    public function getAdjustments(?string $type = null): Collection
    {
        if (null === $type) {
            return $this->adjustments;
        }

        return $this->adjustments->filter(function (AdjustmentInterface $adjustment) use ($type) {
            return $type === $adjustment->getType();
        });
    }

    /**
     * {@inheritdoc}
     */
    public function getAdjustmentsRecursively(?string $type = null): Collection
    {
        $adjustments = clone $this->getAdjustments($type);

        foreach ($this->units as $unit) {
            foreach ($unit->getAdjustments($type) as $adjustment) {
                $adjustments->add($adjustment);
            }
        }

        return $adjustments;
    }

    /**
     * {@inheritdoc}
     */
    public function addAdjustment(AdjustmentInterface $adjustment): void
    {
        if (!$this->hasAdjustment($adjustment)) {
            $this->adjustments->add($adjustment);
            $this->addToAdjustmentsTotal($adjustment);
            $adjustment->setAdjustable($this);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function removeAdjustment(AdjustmentInterface $adjustment): void
    {
        if (!$adjustment->isLocked() && $this->hasAdjustment($adjustment)) {
            $this->adjustments->removeElement($adjustment);
            $this->subtractFromAdjustmentsTotal($adjustment);
            $adjustment->setAdjustable(null);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function hasAdjustment(AdjustmentInterface $adjustment): bool
    {
        return $this->adjustments->contains($adjustment);
    }

    /**
     * {@inheritdoc}
     */
    public function getAdjustmentsTotal(?string $type = null): int
    {
        if (null === $type) {
            return $this->adjustmentsTotal;
        }

        $total = 0;
        foreach ($this->getAdjustments($type) as $adjustment) {
            if (!$adjustment->isNeutral()) {
                $total += $adjustment->getAmount();
            }
        }

        return $total;
    }

    /**
     * {@inheritdoc}
     */
    public function getAdjustmentsTotalRecursively(?string $type = null): int
    {
        $total = 0;

        foreach ($this->getAdjustmentsRecursively($type) as $adjustment) {
            if (!$adjustment->isNeutral()) {
                $total += $adjustment->getAmount();
            }
        }

        return $total;
    }

    /**
     * {@inheritdoc}
     */
    public function removeAdjustments(?string $type = null): void
    {
        foreach ($this->getAdjustments($type) as $adjustment) {
            $this->removeAdjustment($adjustment);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function removeAdjustmentsRecursively(?string $type = null): void
    {
        $this->removeAdjustments($type);
        foreach ($this->units as $unit) {
            $unit->removeAdjustments($type);
        }
    }

    /**
     * Recalculates total after units total or adjustments total change.
     */
    protected function recalculateTotal(): void
    {
        $this->total = $this->unitsTotal + $this->adjustmentsTotal;

        if ($this->total < 0) {
            $this->total = 0;
        }

        if (null !== $this->order) {
            $this->order->recalculateItemsTotal();
        }
    }

    protected function addToAdjustmentsTotal(AdjustmentInterface $adjustment): void
    {
        if (!$adjustment->isNeutral()) {
            $this->adjustmentsTotal += $adjustment->getAmount();
            $this->recalculateTotal();
        }
    }

    protected function subtractFromAdjustmentsTotal(AdjustmentInterface $adjustment): void
    {
        if (!$adjustment->isNeutral()) {
            $this->adjustmentsTotal -= $adjustment->getAmount();
            $this->recalculateTotal();
        }
    }

    /** @var ProductVariantInterface */
    protected $variant;

    /** @var string */
    protected $productName;

    /** @var string */
    protected $variantName;

    /**
     * {@inheritdoc}
     */
    public function getVariant(): ?ProductVariantInterface
    {
        return $this->variant;
    }

    /**
     * {@inheritdoc}
     */
    public function setVariant(?ProductVariantInterface $variant): void
    {
        $this->variant = $variant;
    }

    public function getProduct(): ?ProductInterface
    {
        return $this->variant->getProduct();
    }

    /**
     * {@inheritdoc}
     */
    public function getProductName(): ?string
    {
        return $this->productName ?: $this->variant->getProduct()->getName();
    }

    /**
     * {@inheritdoc}
     */

src/AppBundle/Form/ImportType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Import;
use AppBundle\Entity\Restaurant;
use Sylius\Component\Core\Model\Channel;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ImportType extends AbstractType
{

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pricesDate', DateType::class, [
                'label' => 'sylius.form.import.prices.date',
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'disabled' => false,
                'html5' => true,
            ])
            ->add('filename', TextType::class, [
                'label' => 'sylius.form.import.filename',
            ])
            ->add('fetcher', TextType::class, [
                'label' => 'sylius.form.import.fetcher',
            ])
            ->add('channel', EntityType::class, [
                'label' => 'sylius.form.import.channel',
                'class' => Channel::class,
            ])
            ->add('Restaurant', EntityType::class, [
                'label' => 'sylius.form.import.restaurant',
                'class' => Restaurant::class,
                'required' => false,
            ])
//            ->add('lines', CollectionType::class, [
//                'entry_type' => ImportLineType::class
//            ])
            ->getForm();
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Import::class,
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'vitalis_import_type';
    }
}

src/AppBundle/Resources/views/Admin/SupplierPrices/_blocked_price_form.html.twig
<div id="blocked-price-segment" class="ui basic segment">
    <div class="ui inverted dimmer">
        <div class="ui text loader">Chargement des infos (prix, poids) pour cette variante...</div>
    </div>
    <div class="ui fluid card">
        <div class="content">
            <div class="header">Ajouter un prix bloqué</div>
            <div class="description">
                {{ form_start(blockedPriceForm, {attr: {id: 'blocked-price-form', class: 'ui form'}}) }}
                <div class="ui grid">
                    <div class="row">
                        <div class="eight wide column">
                            {{ form_row(blockedPriceForm.productVariant) }}
                            {{ form_row(blockedPriceForm.kgPrice) }}
                            {{ form_row(blockedPriceForm.unitPrice) }}
                            {{ form_row(blockedPriceForm.validFrom) }}
                            {{ form_row(blockedPriceForm.validTo) }}
                            {{ form_widget(blockedPriceForm.weight) }}
                        </div>

                        <div class="eight wide column">
                            {{ form_row(blockedPriceForm.optionValues) }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="column center aligned">
                            <button type="submit" id="submit-blocked-price" class="ui positive button">Créer le prix bloqué</button>
                        </div>
                    </div>
                </div>
                {{ form_end(blockedPriceForm) }}
            </div>
        </div>
    </div>
</div>

src/AppBundle/Resources/views/Admin/SupplierPrices/_foodomarket_prices.html.twig
<table class="ui sortable celled striped table">
    <thead>
        <tr>
            <th class="collapsing"></th>
            <th class="collapsing">ID</th>
            <th class="collapsing">Référence</th>
            <th class="sorted ascending collapsing">Produit</th>
            <th style="width: 120px; min-width: 120px;">Poids</th>
            <th style="width: 60px; min-width: 60px;">Quantité</th>
            <th style="width: 60px; min-width: 60px;">UM</th>
            <th style="width: 120px; min-width: 120px;">Prix kilo</th>
            <th style="width: 120px; min-width: 120px;">Prix unitaire</th>
            <th class="collapsing">Promo</th>
            <th class="collapsing"></th>
        </tr>
    </thead>
    <tbody>
        {% for price in prices %}
            <tr>
                <td class="collapsing">
                    <img src="{{ price.productImage|imagine_filter('front_tiny') }}"/>
                </td>
                <td class="collapsing">{{ price.productId }}</td>
                <td class="collapsing">{{ price.reference }}</td>
                <td class="collapsing">{{ price.product }}</td>
                <td class="collapsing">
                    <div class="ui fluid right labeled input">
                        <input type="number" class="weight" placeholder="Poids" value="{{ price.weight }}">
                        <label class="ui label">KG</label>
                    </div>
                </td>
                <td class="collapsing">
                    <div class="ui fluid input">
                        <input type="number" class="quantity" placeholder="Nombre d'unités" value="{{ price.quantity }}">
                    </div>
                </td>
                <td class="collapsing">
                    <div class="ui fluid input">
                        <input type="text" class="um" placeholder="Unité de mesure" value="{{ price.um }}">
                    </div>
                </td>
                <td>
                    <div class="ui fluid right labeled input">
                        <input type="number" class="kg-price" placeholder="Prix kilo" value="{{ price.kgPrice }}">
                        <label class="ui label">€</label>
                    </div>
                </td>
                <td>
                    <div class="ui fluid right labeled input">
                        <input type="number" class="unit-price" placeholder="Prix unitaire" value="{{ price.unitPrice }}">
                        <label class="ui label">€</label>
                    </div>
                </td>
                <td>
                    <button class="ui labeled icon button toggle-promo {% if price.promo %}positive{% else %}negative{% endif  %}" data-price-id="{{ price.id }}">
                        <i class="{% if price.promo %}checkmark{% else %}close{% endif %} icon"></i>
                        {% if price.promo %}Oui{% else %}Non{% endif %}
                    </button>
                </td>
                <td class="right aligned collapsing">
                    <button type="button" role="button" class="ui button primary update-price" data-price-id="{{ price.id }}">Mettre à jour</button>
                    <a type="button" role="button" class="ui button secondary view-history" href="{{ path('app_admin_supplier_prices_history', {id: price.id}) }}">Historique</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

src/AppBundle/Resources/views/Admin/SupplierPrices/_restaurant_prices.html.twig
{% if prices is not empty %}
    <table class="ui sortable celled striped table">
        <thead>
            <tr>
                <th class="collapsing">Référence</th>
                <th class="sorted ascending collapsing">Produit</th>
                <th class="collapsing">Poids</th>
                <th>Prix kilo</th>
                <th>Prix unitaire</th>
                <th>Début de validité</th>
                <th>Fin de validité</th>
                <th class="collapsing"></th>
            </tr>
        </thead>
        <tbody>
            {% for price in prices %}
                <tr>
                    <td class="collapsing">{{ price.reference }}</td>
                    <td class="collapsing">{{ price.product }}</td>
                    <td class="collapsing">{{ price.weight }}KG</td>
                    <td>
                        <div class="ui fluid right labeled input">
                            <input type="number" class="kg-price" placeholder="Prix kilo" value="{{ price.kgPrice }}" data-weight="{{ price.weight }}">
                            <label class="ui label">€</label>
                        </div>
                    </td>
                    <td>
                        <div class="ui fluid right labeled input">
                            <input type="number" class="unit-price" placeholder="Prix unitaire" value="{{ price.unitPrice }}" data-weight="{{ price.weight }}">
                            <label class="ui label">€</label>
                        </div>
                    </td>

                    <td>
                        <div class="ui fluid input">
                            <input type="date" class="valid-from" placeholder="Début de validité" value="{{ price.validFrom }}">
                        </div>
                    </td>

                    <td>
                        <div class="ui fluid input">
                            <input type="date" class="valid-to" placeholder="Fin de validité" value="{{ price.validTo }}">
                        </div>
                    </td>

                    <td class="right aligned collapsing">
                        {#<button type="button" role="button" class="ui button primary update-price" data-price-id="{{ price.id }}">Mettre à jour</button>#}
                        <button type="button" role="button" class="ui button primary edit-price" data-price-id="{{ price.id }}">&Eacute;diter</button>
                        <button type="button" role="button" class="ui button negative delete-price" data-price-id="{{ price.id }}">Supprimer</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="ui info message">
        <div class="content">
            <div class="header">Pas de prix bloqués</div>
            <p>Ce restaurant n'a pas de prix bloqué. On peut en ajouter avec le formulaire ci-dessous</p>
        </div>
    </div>
{% endif %}

{% include '@App/Admin/SupplierPrices/_blocked_price_form.html.twig' %}

src/AppBundle/Resources/views/Admin/SupplierPrices/bench.html.twig
{% extends 'SyliusAdminBundle::layout.html.twig' %}

{% block content %}
    <div class="ui grid">
        <div class="row">
            <div class="sixteen wide column">
                <h1 class="ui dividing header left floated">Bench des produits pour le fournisseur partenaire &laquo;{{ supplier }}&raquo;</h1>
                <a class="ui button right floated" href="{{ path('app_admin_supplier_prices_index') }}">Retour à la liste des fournisseurs</a>
            </div>
        </div>

        <div class="row">
            <div class="sixteen wide column">
                <table class="ui table">
                    <thead>
                    <tr>
                        {% for supplier in bench[0] %}
                            <th>{{ supplier }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for products in bench %}
                        {% if not loop.first %}
                            <tr>
                                {% for product in products %}
                                <td>{{ product }}</td>
                                {% endfor %}
                            </tr>
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

src/AppBundle/Resources/views/Admin/SupplierPrices/history.html.twig
{% extends 'SyliusAdminBundle::layout.html.twig' %}

{% block content %}
    <div class="ui grid">
        <div class="row">
            <div class="column">
                <div class="ui dividing header">Historique des prix du produit {{ product }} chez {{ supplier }}</div>
            </div>
        </div>

        <div class="row">
            <div class="column">
                <div class="ui message">
                    <div class="content">
                        <div class="header">Synthèse</div>
                        <p>
                            {% for s in synthesis %}
                                Du {{ s.from }} au {{ s.to }}: ({{ s.id }}) {{ s.name }}<br/>
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="column">
                <div class="ui list">
                {#{% for price in history %}#}
                    {#<div class="item">#}
                        {#Variante #{{ price.productVariant.id }}: {{ price.productVariant.fullDisplayName }} - {{ price.productVariant.explicitContent }} - {{ price.productVariant.displayOrigin }}#}
                        {#<br/>#}
                        {#Prix: {{ price.kgPrice / 100 }}€/KG - {{ price.unitPrice / 100 }}€/PC#}
                    {#</div>#}
                {#{% endfor %}#}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

src/AppBundle/Resources/views/Admin/SupplierPrices/index.html.twig
{% extends 'SyliusAdminBundle::layout.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('bundles/app/js/tablesort.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#suppliers-table').tablesort();
        });
    </script>
{% endblock %}

{% block content %}
    <div class="ui grid">
        <div class="row">
            <div class="column">
                <h1 class="ui dividing header">Gestion des prix par fournisseur</h1>
            </div>
        </div>

        <div class="row">
            <div class="ui sixteen wide column">
                <table id="suppliers-table" class="ui sortable striped table">
                    <thead>
                        <tr>
                            <th class="sorted ascending">Fournisseur</th>
                            <th class="center aligned">Statistiques</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for supplier in suppliers %}
                            <tr>
                                <td>{{ supplier.name }}</td>
                                <td class="center aligned">
                                    <div class="ui three mini statistics">
                                        <div class="statistic">
                                            <div class="value">
                                                {{ supplier.products }}
                                            </div>
                                            <div class="label">
                                                Produits
                                            </div>
                                        </div>

                                        <div class="statistic">
                                            <div class="value">
                                                {{ supplier.clients }}
                                            </div>
                                            <div class="label">
                                                Clients
                                            </div>
                                        </div>

                                        <div class="statistic">
                                            <div class="value">
                                                {{ supplier.restaurants }}
                                            </div>
                                            <div class="label">
                                                Restaurants
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="ui three buttons">
                                        <a href="{{ path('app_admin_supplier_prices_foodomarket_edit', {id: supplier.id}) }}" class="ui basic green button edit-foodomarket-prices">Editer les prix FoodoMarket</a>
                                        <a href="{{ path('app_admin_supplier_prices_restaurant_edit', {id: supplier.id}) }}" class="ui basic red button edit-restaurant-prices">Editer les prix restaurant</a>
                                        <a href="{{ path('app_admin_supplier_prices_bench', {id: supplier.id}) }}" class="ui basic blue button bench-prices">Bench</a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/SupplierPrices/restaurant_edit.html.twig
{% extends 'SyliusAdminBundle::layout.html.twig' %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block content %}
    <div class="ui grid">
        <div class="row">
            <div class="sixteen wide column">
                <h1 class="ui dividing header left floated">Gestion des prix bloqués pour le fournisseur partenaire &laquo;{{ supplier }}&raquo;</h1>
                <a class="ui button right floated" href="{{ path('app_admin_supplier_prices_index') }}">Retour à la liste des fournisseurs</a>
            </div>
        </div>

        <div class="row">
            <div class="sixteen wide column">
                <h3 class="ui dividing header">Choisir un restaurant dans la liste pour éditer ses prix</h3>

                <div class="ui relaxed divided list">
                    {% for restaurant in restaurants %}
                        <div class="item">
                            <div class="content">
                                <a class="header restaurant" href="{{ path('app_admin_supplier_prices_restaurant_prices_edit', {id: restaurant.id, supplierId: supplierId}) }}">
                                    {{ restaurant.name }}
                                </a>
                                <div class="description">
                                    {{ restaurant.address }}<br/>
                                    Créé le {{ restaurant.createdAt }}

                                    {% if restaurant.nbBlockedPrice > 0 %}
                                        <span class="right floated"><b>{{ restaurant.nbBlockedPrice }} prix bloqués</b></span>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}